---
title: "Week 1 Homework NJ"
format: html 
Author: "Natalie Jacobs" 
---


# Problem 1
We installed PeacoQC during this session, but we didn’t have time to explore what functions are present within the package. Using what you have learned about accessing documentation, figure out and list what functions it contains

# Answer 1

```{r}
library(PeacoQC)
ls("package:PeacoQC")
```

# output 
[1] "PeacoQC" "PeacoQCHeatmap" "PlotPeacoQC" "RemoveDoublets" "RemoveMargins" 

# Problem 2

Take a closer look at the list of Bioconductor cytometry packages. Report back on how many there are currently in Bioconductor, the author/maintainer with the most contributed cytometry R packages, and a couple packages that you would be interested in exploring more in-depth later in the course.

# Answer 2

There are over 2,361 packages listed on Bioconductor.org. 

Hervé Pagès maintains a lot of highly ranked packages, so does Guangchuang Yu, and Aaron Lun

TENxPBMCData, SamSPECTRAL, cytofWorkflow, RNAseq123, rnaseqGene, GEOMxWorkflows packages looks interesting 

# Problem 3
There is another way to install R packages, using the newer pak package. Positron uses this when installing suggested dependencies. After learning more about it via the documentation and it’s pkgdown website, I would like you to attempt to install the following three R packages using this newer method: “broom”, “cytoMEM”, “DillonHammill/CytoExploreR”.
Take screenshots, and in a new quarto markdown document, describe how the installation process differed from what you saw for install.packages(), install() and install_github().

# Answer 3 

Broom and cytoMEM installed easily without having to know if from CRAN or Bioconductor. I wasn’t able to install DillonHammill/CytoExploreR with pak method because of an error with package dependencies. I tried install.packages but the package was not available for this version of R. 
